### ISSUE TITLE
后端代码

### ISSUE THREAD

**Issue by lionellc** [gorkys/realboxVue#1]
您好，对您开源的广告机代码很感兴趣，您这是仅前端代码吗，mock数据也没有更新。请问有没有途径可以提供后端代码，我可以在参考后为您提供mock。联系方式：lionel_lc@163.com。谢谢~

**Comment by gorkys** [comment]
该项目在重构中，但是在无论何时，后端代码都无法提供。不好意思~

**Comment by lionellc** [comment]
那请问有没有合作的机会，个人层面或者公司层面。有意向希望可以联系我，告知联系方式。

**Comment by gorkys** [comment]
@lionel-lc 已通过邮箱方式联系。
